[aws]
aws_access_key_id = "AKIAQELR7CCQJ7SNXWOG"
aws_secret_access_key = "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"
region = "us-east-2"
athena_database = "gold_db_iptu"
athena_workgroup = "primary"
s3_output = "s3://datalake-athena-resultados-iptu-recife/"